In [1]:
!pip install qiskit qiskit-aer -q

In [2]:
import random
import numpy as np

from qiskit import QuantumCircuit
from qiskit.quantum_info import Statevector
from qiskit_aer import AerSimulator

/var/folders/yp/078pyxw11mq6g7sd_2ty18z80000gn/T/ipykernel_27352/2087795024.py:4: DeprecationWarning: Using Qiskit with Python 3.9 is deprecated as of the 2.1.0 release. Support for running Qiskit with Python 3.9 will be removed in the 2.3.0 release, which coincides with when Python 3.9 goes end of life.
  from qiskit import QuantumCircuit


In [3]:
def show_state(circuit, title):
    state = Statevector.from_instruction(circuit)
    print("="*60)
    print(title)
    print(circuit.draw())
    print("\nStatevector:")
    print(state)
    print("="*60)
    return state

In [4]:
qc_hzh = QuantumCircuit(1)

qc_hzh.h(0)

qc_hzh.z(0)

qc_hzh.h(0)

state_hzh = show_state(qc_hzh,"HZH Circuit")

HZH Circuit
   ┌───┐┌───┐┌───┐
q: ┤ H ├┤ Z ├┤ H ├
   └───┘└───┘└───┘

Statevector:
Statevector([-2.23711432e-17+0.j,  1.00000000e+00+0.j],
            dims=(2,))


In [5]:
qc_x2 = QuantumCircuit(1)

qc_x2.x(0)

state_x2 = show_state(qc_x2,"X Gate Circuit")

X Gate Circuit
   ┌───┐
q: ┤ X ├
   └───┘

Statevector:
Statevector([0.+0.j, 1.+0.j],
            dims=(2,))


In [6]:
print("HZH State:")
print(state_hzh.data)

print("\nX Gate State:")
print(state_x2.data)

print("\nEquivalent?")

print(np.allclose(state_hzh.data,state_x2.data))

HZH State:
[-2.23711432e-17+0.j  1.00000000e+00+0.j]

X Gate State:
[0.+0.j 1.+0.j]

Equivalent?
True


In [7]:
print("Analytical Proof")

print()

print("Hadamard Matrix:")

print(np.array([[1,1],[1,-1]])/np.sqrt(2))

print()

print("Z Matrix:")

print(np.array([[1,0],[0,-1]]))

print()

print("X Matrix:")

print(np.array([[0,1],[1,0]]))

print()

H = np.array([[1,1],[1,-1]])/np.sqrt(2)

Z = np.array([[1,0],[0,-1]])

HZH = H @ Z @ H

print("HZH Matrix:")

print(HZH)

print()

print("Is HZH equal to X?")

print(np.allclose(HZH,np.array([[0,1],[1,0]])))

Analytical Proof

Hadamard Matrix:
[[ 0.70710678  0.70710678]
 [ 0.70710678 -0.70710678]]

Z Matrix:
[[ 1  0]
 [ 0 -1]]

X Matrix:
[[0 1]
 [1 0]]

HZH Matrix:
[[-2.23711432e-17  1.00000000e+00]
 [ 1.00000000e+00 -2.23711432e-17]]

Is HZH equal to X?
True
